import { localStorageService } from '../services/localStorage';

export const BeliefStore = localStorageService.entities.BeliefStore;
export const PipelineRun = localStorageService.entities.PipelineRun;
export const MindBiography = localStorageService.entities.MindBiography;
export const WorldModel = localStorageService.entities.WorldModel;
export const CuriosityItem = localStorageService.entities.CuriosityItem;
export const GoalItem = localStorageService.entities.GoalItem;
export const TemporalEvent = localStorageService.entities.TemporalEvent;
export const FeedbackItem = localStorageService.entities.FeedbackItem;
export const TrainingRun = localStorageService.entities.TrainingRun;
export const DreamRun = localStorageService.entities.DreamRun;
export const EmergenceEvent = localStorageService.entities.EmergenceEvent;
export const LongTermMemory = localStorageService.entities.LongTermMemory;
export const Dataset = localStorageService.entities.Dataset;
export const ScheduledTask = localStorageService.entities.ScheduledTask;
export const ConversationMessage = localStorageService.entities.ConversationMessage;
export const SelfLedgerRevision = localStorageService.entities.SelfLedgerRevision;
export const BeliefTension = localStorageService.entities.BeliefTension;
export const UserModelSnapshot = localStorageService.entities.UserModelSnapshot;
export const ConsolidationDigest = localStorageService.entities.ConsolidationDigest;
export const PendingMindUpdate = localStorageService.entities.PendingMindUpdate;
export const ExecutionLog = localStorageService.entities.ExecutionLog;

/** Playground mirror mind (System B) — separate IndexedDB entity namespaces. */
export const MirrorBeliefStore = localStorageService.entitiesMirror.BeliefStore;
export const MirrorPipelineRun = localStorageService.entitiesMirror.PipelineRun;
export const MirrorMindBiography = localStorageService.entitiesMirror.MindBiography;
export const MirrorWorldModel = localStorageService.entitiesMirror.WorldModel;
export const MirrorCuriosityItem = localStorageService.entitiesMirror.CuriosityItem;
export const MirrorGoalItem = localStorageService.entitiesMirror.GoalItem;
export const MirrorTemporalEvent = localStorageService.entitiesMirror.TemporalEvent;
export const MirrorConversationMessage = localStorageService.entitiesMirror.ConversationMessage;
export const MirrorEmergenceEvent = localStorageService.entitiesMirror.EmergenceEvent;
export const MirrorLongTermMemory = localStorageService.entitiesMirror.LongTermMemory;
export const MirrorSelfLedgerRevision = localStorageService.entitiesMirror.SelfLedgerRevision;
export const MirrorBeliefTension = localStorageService.entitiesMirror.BeliefTension;
export const MirrorUserModelSnapshot = localStorageService.entitiesMirror.UserModelSnapshot;
export const MirrorConsolidationDigest = localStorageService.entitiesMirror.ConsolidationDigest;
export const MirrorFeedbackItem = localStorageService.entitiesMirror.FeedbackItem;
export const MirrorDreamRun = localStorageService.entitiesMirror.DreamRun;
export const MirrorPendingMindUpdate = localStorageService.entitiesMirror.PendingMindUpdate;
