/** Shown in Settings for onboarding (plain text). */
export const LOCAL_LLM_SETUP_TEXT = [
  'This app uses a local OpenAI-compatible server only (no cloud LLM keys). LM Studio is the recommended setup.',
  '',
  '--- LM Studio ---',
  '1. Install LM Studio from https://lmstudio.ai and open it.',
  '2. Download a model: use the search / Hugging Face tab, pick a GGUF, and download a size your GPU or CPU can run.',
  '3. Open the model in the chat pane (click it so it is loaded), or use the developer "Load" flow so the weights are ready.',
  '4. Go to the "Local Server" tab (or "Developer" → local server, depending on your LM Studio version).',
  '5. Select the same model in the server dropdown, then click "Start Server".',
  '   Default URL is usually http://127.0.0.1:1234 — you may paste the base without /v1 (the backend adds it if missing).',
  '6. Copy the exact model identifier LM Studio shows for the API (often visible next to the server status or in the',
  '   server panel). Put that string in LOCAL_LLM_MODELS — it must match what the local server expects.',
  '7. In project root .env:',
  '   LOCAL_LLM_BASE_URL=http://127.0.0.1:1234',
  '   LOCAL_LLM_MODELS=<paste the model id from LM Studio, e.g. google_gemma-3-4b-it>',
  '   LM_API_TOKEN=<token from LM Studio Developer → Server, if auth is enabled>',
  '   LOCAL_LLM_LOW_SPEC=1   (recommended on slow laptops — smaller prompts, easier timeouts)',
  '   LOCAL_LLM_TIMEOUT_MS=3600000   (optional; default is 30 minutes per LLM call if unset)',
  '8. Restart the backend. Run Graph Pipeline — requests go to your machine only.',
  '',
  '--- Ollama (optional) ---',
  '1. Install from https://ollama.com and keep the app running (API on port 11434 by default).',
  '2. In a terminal: ollama pull llama3.2   (or another model name you prefer)',
  '3. In project root .env:',
  '   LOCAL_LLM_BASE_URL=http://127.0.0.1:11434',
  '   LOCAL_LLM_MODELS=llama3.2',
  '   LM_API_TOKEN=ollama   (or any non-empty string if your server expects a Bearer token)',
  '4. Restart the backend (e.g. npm run dev).',
  '',
  'Tip: If calls fail with "model not found", LOCAL_LLM_MODELS does not match the loaded model id.',
  'Tip: Keep the local server running while you use MyBrain.',
].join('\n');
