/**
 * Primary vs playground mirror (System B) entity manager maps for UI pages.
 */
import {
  BeliefStore,
  BeliefTension,
  PipelineRun,
  MindBiography,
  WorldModel,
  CuriosityItem,
  GoalItem,
  TemporalEvent,
  EmergenceEvent,
  LongTermMemory,
  ConversationMessage,
  SelfLedgerRevision,
  UserModelSnapshot,
  ConsolidationDigest,
  FeedbackItem,
  DreamRun,
  MirrorBeliefStore,
  MirrorBeliefTension,
  MirrorPipelineRun,
  MirrorMindBiography,
  MirrorWorldModel,
  MirrorCuriosityItem,
  MirrorGoalItem,
  MirrorTemporalEvent,
  MirrorConversationMessage,
  MirrorEmergenceEvent,
  MirrorLongTermMemory,
  MirrorSelfLedgerRevision,
  MirrorUserModelSnapshot,
  MirrorConsolidationDigest,
  MirrorFeedbackItem,
  MirrorDreamRun,
  MirrorPendingMindUpdate,
  PendingMindUpdate,
} from './data';

export const primaryEntities = {
  BeliefStore,
  BeliefTension,
  PipelineRun,
  MindBiography,
  WorldModel,
  CuriosityItem,
  GoalItem,
  TemporalEvent,
  EmergenceEvent,
  LongTermMemory,
  ConversationMessage,
  SelfLedgerRevision,
  UserModelSnapshot,
  ConsolidationDigest,
  FeedbackItem,
  DreamRun,
  PendingMindUpdate,
};

export const mirrorEntities = {
  BeliefStore: MirrorBeliefStore,
  BeliefTension: MirrorBeliefTension,
  PipelineRun: MirrorPipelineRun,
  MindBiography: MirrorMindBiography,
  WorldModel: MirrorWorldModel,
  CuriosityItem: MirrorCuriosityItem,
  GoalItem: MirrorGoalItem,
  TemporalEvent: MirrorTemporalEvent,
  EmergenceEvent: MirrorEmergenceEvent,
  LongTermMemory: MirrorLongTermMemory,
  ConversationMessage: MirrorConversationMessage,
  SelfLedgerRevision: MirrorSelfLedgerRevision,
  UserModelSnapshot: MirrorUserModelSnapshot,
  ConsolidationDigest: MirrorConsolidationDigest,
  FeedbackItem: MirrorFeedbackItem,
  DreamRun: MirrorDreamRun,
  PendingMindUpdate: MirrorPendingMindUpdate,
};
